import { fileURLToPath } from 'node:url'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { '@': fileURLToPath(new URL('./web/src', import.meta.url)) },
  },
  test: {
    globals: true,
    include: ['test/**/*.test.ts', 'web/test/**/*.test.{ts,tsx}'],
    setupFiles: ['web/test/setup.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts', 'web/src/**/*.{ts,tsx}'],
      // Vendored shadcn/ui component source: generated by the CLI and left
      // unmodified, so it is third-party code we do not test. The exclusion
      // holds ONLY while a file is unmodified — edit one and it must move out
      // of components/ui/ and meet the 90% bar (decision-00001 §4).
      exclude: ['web/src/main.tsx', 'web/src/components/ui/**'],
      thresholds: { lines: 90, branches: 90, functions: 90 },
    },
  },
})
